server:
  port: ${ADAPTER_PORT:9001}

spring:
  flyway:
    schemas: public
    enabled: true
  datasource:
    url: ${DATA_SOURCE:jdbc:postgresql://localhost:5435/costs}
    username: ${DATA_SOURCE_USERNAME:marvin}
    password: ${DATA_SOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camt:
  import:
    file:
      in: ${CAMT_DIRECTORY_IN:./app/camt}
      done: ${CAMT_DIRECTORY_DONE:./app/camt/done}
    costs:
      special:
        limit: 50

importer:
  in:
    costs: ${IMPORTER_IN_COSTS:./app/import/costs}
  done: ${IMPORTER_DONE:./app/import/done}

backup:
  upload:
    enabled: ${BACKUP_UPLOAD_ENABLED:false}
    watch-dir: ${BACKUP_WATCH_DIR:./app/backup/in}
    done-dir: ${BACKUP_DONE_DIR:./app/backup/done}
    error-dir: ${BACKUP_ERROR_DIR:./app/backup/error}
    drive-folder-name: ${BACKUP_DRIVE_FOLDER:db-backups}

uploader:
  enabled: false
  credentials:
    path: ${UPLOADER_CREDENTIALS_PATH:./app/google/credentials.json}
  cost-export-folder: ${UPLOADER_COST_EXPORT_FOLDER:./app/export}
  parent-folder-name: db-backups

influxdb:
  #  url: ${INFLUX_URL:http://localhost:8086}
  #  token: ${INFLUX_TOKEN:temp-init-token-will-be-replaced}
  url: ${INFLUX_URL:http://influxdb.home-lab.com}
  token: ${INFLUX_TOKEN:rmz5aaaKYSpgvXSO3C1UFZmXjvtpwI81b7hcMaMJJqOTjvgI82iNAbSsF7fpGIy2fduNDKACQ759cyaiECrulg==}
  org: ${INFLUX_ORG:wildfly_domain}

salary:
  import:
    ibans: ${SALARY_IMPORT_IBANS}
special:
  cost:
    blocked-ibans: ${SPECIAL_COST_BLOCKED_IBANS}
monthly:
  cost:
    blocked-ibans: ${MONTHLY_COST_BLOCKED_IBANS}

logging:
  level:
    org.springframework: INFO

management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "prometheus,info,beans"

rss:
  poll-interval-ms: 1800000

climate:
  outdoor:
    entity-id: ${CLIMATE_OUTDOOR_ENTITY_ID:draussen_temperature}
    humidity-entity-id: ${CLIMATE_OUTDOOR_HUMIDITY_ENTITY_ID:draussen_humidity}
